### ISSUE TITLE
麻烦请教一下如何打包

### ISSUE THREAD

**Issue by kamenrx21** [HiCooper/oss-backend#3]
只用过maven，项目里的gradlebuild文件里面好像没有mainclass

jar {
    enabled = true
    from {
        //添加依懒到打包文件
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
    manifest {
        attributes 'Main-Class': 'com.berry.oss.OSSServiceApplication'
    }
}

加了之后，运行jar包
Caused by: java.io.FileNotFoundException: class path resource [org/quartz/spi/JobFactory.class] cannot be opened because it does not exist

**Comment by HiCooper** [comment]
不需要添加内容即可打包哦
如果安装配置过gradle环境，直接项目下 执行： `gradle build` ,
如果没有gradle环境
windows下， 执行：`gradlew.bat build`
macos or linux 执行： `./gradlew build`

**Comment by kamenrx21** [comment]
大佬我部署在Linux系统上，但是url里面没有值（实际服务器上有这个文件），请问是不是要在哪里配置一下FilePath之类的？我Ctrl+F找不到。请赐教一下，蟹蟹

**Comment by HiCooper** [comment]
方便贴个图？

**Comment by kamenrx21** [comment]
> 方便贴个图？

大佬我搞定了，Linux系统没开防火墙端口。打扰了不好意思
